version: '3'
services:
  leafy-postgres:
    image: studydocker25/leafy-postgres:fb54d9d8f8cc6623a4168f4a02e4d5700ee03670
    volumes:
      - mydata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: always

  leafy-backend:
    build: ./leafy-backend
    image: leafy-backend:5.0.0-compose
    environment:
      - DB_URL=leafy-postgres
    depends_on:
      - leafy-postgres
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: on-failure
      
  leafy-front:
    image: studydocker25/leafy-frontend:f14db6f226617bd959076ae92826e08b324c8b19
    environment:
      - BACKEND_HOST=leafy-backend
    ports:
      - 80:80
    depends_on:
      - leafy-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    restart: on-failure

volumes:
  mydata: